"""add user profile and job breakdown

Revision ID: 181bd925f785
Revises: 
Create Date: 2026-09-16 12:56:33.691815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '181bd925f785'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_migration_internal_statements')
    op.add_column('jobs', sa.Column('stack_match_pct', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('seniority_match_pct', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('location_match_pct', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('NEW', 'APPLIED', 'REJECTED', name='jobstatus'),
               existing_nullable=False)
    op.add_column('users', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('top_skills', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('key_achievements', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('min_salary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('bio_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('min_match_score', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('ix_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('ix_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'min_match_score')
    op.drop_column('users', 'bio_summary')
    op.drop_column('users', 'min_salary')
    op.drop_column('users', 'preferred_location')
    op.drop_column('users', 'key_achievements')
    op.drop_column('users', 'top_skills')
    op.drop_column('users', 'years_experience')
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('NEW', 'APPLIED', 'REJECTED', name='jobstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('jobs', 'location_match_pct')
    op.drop_column('jobs', 'seniority_match_pct')
    op.drop_column('jobs', 'stack_match_pct')
    op.create_table('_migration_internal_statements',
    sa.Column('statement_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statement_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('statement_order', name=op.f('_migration_internal_statements_pkey')),
    sa.UniqueConstraint('statement_id', name=op.f('_migration_internal_statements_statement_id_key'), postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###